# The URL the site will be built for
base_url = "https://rust.audio"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_rss = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true
highlight_theme = "ir-white"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "rust.audio"

taxonomies = [
    # CATEGORY IDEAS:
    # dsp
    # synthesis
    # processing
    # theory
    # gui
    # tutorial
    { name = "topics" },
    { name = "crates" },
    { name = "contributors" },
]

[extra]
logo = "/media/logo.svg"
nav = [ { title = "Topics", url = "/topics" }
      , { title = "Crates", url = "/crates"}
      , { title = "About", url = "/#about"}
      ]
discourse_url = "https://rust-audio.discourse.group/"