# The URL the site will be built for
base_url = "https://rust.audio"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_rss = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true
highlight_theme = "ir-white"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "Rust Audio"

taxonomies = [
]

[extra]
logo = "/media/logo.png"
discourse_url = "https://rust-audio.discourse.group/"
repos_url = "https://api.github.com/orgs/RustAudio/repos"
discord_server_id = "590254806208217089"
discord_invite = "https://discord.gg/8qW6q2k"