[build]
ZOLA_VERSION = "0.6.0"
publish = "public"
command = "sed -i s/ZOLA_VERSION/${ZOLA_VERSION}/g && curl -sL https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar zxv && ./zola build"

[context.deploy-preview]
command = "curl -sL https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar zxv && ./zola build" 